//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirServicio
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegrantesModel", Namespace="http://localhost")]
    public partial class IntegrantesModel : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        private string NommedioField;
        
        private string ApellidoField;
        
        private string SexoField;
        
        private System.DateTime FnacimField;
        
        private System.DateTime FfallecField;
        
        private int CiudadnacField;
        
        private int NacionalidadField;
        
        private int PadreField;
        
        private int MadreField;
        
        private int EsposoField;
        
        private int EsposaField;
        
        private DirServicio.PadreMadreModel[] PadreMadreField;
        
        private DirServicio.CiudadesModel[] Ciudades1Field;
        
        private DirServicio.PaisesModel[] Paises1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nommedio
        {
            get
            {
                return this.NommedioField;
            }
            set
            {
                this.NommedioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Fnacim
        {
            get
            {
                return this.FnacimField;
            }
            set
            {
                this.FnacimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Ffallec
        {
            get
            {
                return this.FfallecField;
            }
            set
            {
                this.FfallecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Ciudadnac
        {
            get
            {
                return this.CiudadnacField;
            }
            set
            {
                this.CiudadnacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Nacionalidad
        {
            get
            {
                return this.NacionalidadField;
            }
            set
            {
                this.NacionalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Padre
        {
            get
            {
                return this.PadreField;
            }
            set
            {
                this.PadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Madre
        {
            get
            {
                return this.MadreField;
            }
            set
            {
                this.MadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int Esposo
        {
            get
            {
                return this.EsposoField;
            }
            set
            {
                this.EsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Esposa
        {
            get
            {
                return this.EsposaField;
            }
            set
            {
                this.EsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public DirServicio.PadreMadreModel[] PadreMadre
        {
            get
            {
                return this.PadreMadreField;
            }
            set
            {
                this.PadreMadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public DirServicio.CiudadesModel[] Ciudades1
        {
            get
            {
                return this.Ciudades1Field;
            }
            set
            {
                this.Ciudades1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public DirServicio.PaisesModel[] Paises1
        {
            get
            {
                return this.Paises1Field;
            }
            set
            {
                this.Paises1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PadreMadreModel", Namespace="http://localhost")]
    public partial class PadreMadreModel : object
    {
        
        private int IdField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadesModel", Namespace="http://localhost")]
    public partial class CiudadesModel : object
    {
        
        private int IdCiudadField;
        
        private string CodigoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCiudad
        {
            get
            {
                return this.IdCiudadField;
            }
            set
            {
                this.IdCiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaisesModel", Namespace="http://localhost")]
    public partial class PaisesModel : object
    {
        
        private int IdPaisesField;
        
        private string CodigoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPaises
        {
            get
            {
                return this.IdPaisesField;
            }
            set
            {
                this.IdPaisesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost", ConfigurationName="DirServicio.WebService1Soap")]
    public interface WebService1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtenerConsultaJson", ReplyAction="*")]
        System.Threading.Tasks.Task<DirServicio.ObtenerConsultaJsonResponse> ObtenerConsultaJsonAsync(DirServicio.ObtenerConsultaJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtenerIntegrantesJson", ReplyAction="*")]
        System.Threading.Tasks.Task<DirServicio.ObtenerIntegrantesJsonResponse> ObtenerIntegrantesJsonAsync(DirServicio.ObtenerIntegrantesJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtenerIntegrantes", ReplyAction="*")]
        System.Threading.Tasks.Task<DirServicio.ObtenerIntegrantesResponse> ObtenerIntegrantesAsync(DirServicio.ObtenerIntegrantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/InsertarNuevoIntegrate", ReplyAction="*")]
        System.Threading.Tasks.Task<DirServicio.InsertarNuevoIntegrateResponse> InsertarNuevoIntegrateAsync(DirServicio.InsertarNuevoIntegrateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ObtenerFamiliares", ReplyAction="*")]
        System.Threading.Tasks.Task<DirServicio.ObtenerFamiliaresResponse> ObtenerFamiliaresAsync(DirServicio.ObtenerFamiliaresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerConsultaJsonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerConsultaJson", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerConsultaJsonRequestBody Body;
        
        public ObtenerConsultaJsonRequest()
        {
        }
        
        public ObtenerConsultaJsonRequest(DirServicio.ObtenerConsultaJsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerConsultaJsonRequestBody
    {
        
        public ObtenerConsultaJsonRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerConsultaJsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerConsultaJsonResponse", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerConsultaJsonResponseBody Body;
        
        public ObtenerConsultaJsonResponse()
        {
        }
        
        public ObtenerConsultaJsonResponse(DirServicio.ObtenerConsultaJsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class ObtenerConsultaJsonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerConsultaJsonResult;
        
        public ObtenerConsultaJsonResponseBody()
        {
        }
        
        public ObtenerConsultaJsonResponseBody(string ObtenerConsultaJsonResult)
        {
            this.ObtenerConsultaJsonResult = ObtenerConsultaJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegrantesJsonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegrantesJson", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerIntegrantesJsonRequestBody Body;
        
        public ObtenerIntegrantesJsonRequest()
        {
        }
        
        public ObtenerIntegrantesJsonRequest(DirServicio.ObtenerIntegrantesJsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerIntegrantesJsonRequestBody
    {
        
        public ObtenerIntegrantesJsonRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegrantesJsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegrantesJsonResponse", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerIntegrantesJsonResponseBody Body;
        
        public ObtenerIntegrantesJsonResponse()
        {
        }
        
        public ObtenerIntegrantesJsonResponse(DirServicio.ObtenerIntegrantesJsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class ObtenerIntegrantesJsonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerIntegrantesJsonResult;
        
        public ObtenerIntegrantesJsonResponseBody()
        {
        }
        
        public ObtenerIntegrantesJsonResponseBody(string ObtenerIntegrantesJsonResult)
        {
            this.ObtenerIntegrantesJsonResult = ObtenerIntegrantesJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegrantesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegrantes", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerIntegrantesRequestBody Body;
        
        public ObtenerIntegrantesRequest()
        {
        }
        
        public ObtenerIntegrantesRequest(DirServicio.ObtenerIntegrantesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerIntegrantesRequestBody
    {
        
        public ObtenerIntegrantesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegrantesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegrantesResponse", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerIntegrantesResponseBody Body;
        
        public ObtenerIntegrantesResponse()
        {
        }
        
        public ObtenerIntegrantesResponse(DirServicio.ObtenerIntegrantesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class ObtenerIntegrantesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DirServicio.IntegrantesModel[] ObtenerIntegrantesResult;
        
        public ObtenerIntegrantesResponseBody()
        {
        }
        
        public ObtenerIntegrantesResponseBody(DirServicio.IntegrantesModel[] ObtenerIntegrantesResult)
        {
            this.ObtenerIntegrantesResult = ObtenerIntegrantesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarNuevoIntegrateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarNuevoIntegrate", Namespace="http://localhost", Order=0)]
        public DirServicio.InsertarNuevoIntegrateRequestBody Body;
        
        public InsertarNuevoIntegrateRequest()
        {
        }
        
        public InsertarNuevoIntegrateRequest(DirServicio.InsertarNuevoIntegrateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class InsertarNuevoIntegrateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nommedio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fnacim;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ciudadnac;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nacionalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int padre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int madre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int esposo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int esposa;
        
        public InsertarNuevoIntegrateRequestBody()
        {
        }
        
        public InsertarNuevoIntegrateRequestBody(string nombre, string nommedio, string apellido, string sexo, System.DateTime fnacim, int ciudadnac, int nacionalidad, int padre, int madre, int esposo, int esposa)
        {
            this.nombre = nombre;
            this.nommedio = nommedio;
            this.apellido = apellido;
            this.sexo = sexo;
            this.fnacim = fnacim;
            this.ciudadnac = ciudadnac;
            this.nacionalidad = nacionalidad;
            this.padre = padre;
            this.madre = madre;
            this.esposo = esposo;
            this.esposa = esposa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarNuevoIntegrateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarNuevoIntegrateResponse", Namespace="http://localhost", Order=0)]
        public DirServicio.InsertarNuevoIntegrateResponseBody Body;
        
        public InsertarNuevoIntegrateResponse()
        {
        }
        
        public InsertarNuevoIntegrateResponse(DirServicio.InsertarNuevoIntegrateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class InsertarNuevoIntegrateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarNuevoIntegrateResult;
        
        public InsertarNuevoIntegrateResponseBody()
        {
        }
        
        public InsertarNuevoIntegrateResponseBody(string InsertarNuevoIntegrateResult)
        {
            this.InsertarNuevoIntegrateResult = InsertarNuevoIntegrateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFamiliaresRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFamiliares", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerFamiliaresRequestBody Body;
        
        public ObtenerFamiliaresRequest()
        {
        }
        
        public ObtenerFamiliaresRequest(DirServicio.ObtenerFamiliaresRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerFamiliaresRequestBody
    {
        
        public ObtenerFamiliaresRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFamiliaresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFamiliaresResponse", Namespace="http://localhost", Order=0)]
        public DirServicio.ObtenerFamiliaresResponseBody Body;
        
        public ObtenerFamiliaresResponse()
        {
        }
        
        public ObtenerFamiliaresResponse(DirServicio.ObtenerFamiliaresResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost")]
    public partial class ObtenerFamiliaresResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerFamiliaresResult;
        
        public ObtenerFamiliaresResponseBody()
        {
        }
        
        public ObtenerFamiliaresResponseBody(string ObtenerFamiliaresResult)
        {
            this.ObtenerFamiliaresResult = ObtenerFamiliaresResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface WebService1SoapChannel : DirServicio.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DirServicio.WebService1Soap>, DirServicio.WebService1Soap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DirServicio.ObtenerConsultaJsonResponse> DirServicio.WebService1Soap.ObtenerConsultaJsonAsync(DirServicio.ObtenerConsultaJsonRequest request)
        {
            return base.Channel.ObtenerConsultaJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<DirServicio.ObtenerConsultaJsonResponse> ObtenerConsultaJsonAsync()
        {
            DirServicio.ObtenerConsultaJsonRequest inValue = new DirServicio.ObtenerConsultaJsonRequest();
            inValue.Body = new DirServicio.ObtenerConsultaJsonRequestBody();
            return ((DirServicio.WebService1Soap)(this)).ObtenerConsultaJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DirServicio.ObtenerIntegrantesJsonResponse> DirServicio.WebService1Soap.ObtenerIntegrantesJsonAsync(DirServicio.ObtenerIntegrantesJsonRequest request)
        {
            return base.Channel.ObtenerIntegrantesJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<DirServicio.ObtenerIntegrantesJsonResponse> ObtenerIntegrantesJsonAsync()
        {
            DirServicio.ObtenerIntegrantesJsonRequest inValue = new DirServicio.ObtenerIntegrantesJsonRequest();
            inValue.Body = new DirServicio.ObtenerIntegrantesJsonRequestBody();
            return ((DirServicio.WebService1Soap)(this)).ObtenerIntegrantesJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DirServicio.ObtenerIntegrantesResponse> DirServicio.WebService1Soap.ObtenerIntegrantesAsync(DirServicio.ObtenerIntegrantesRequest request)
        {
            return base.Channel.ObtenerIntegrantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DirServicio.ObtenerIntegrantesResponse> ObtenerIntegrantesAsync()
        {
            DirServicio.ObtenerIntegrantesRequest inValue = new DirServicio.ObtenerIntegrantesRequest();
            inValue.Body = new DirServicio.ObtenerIntegrantesRequestBody();
            return ((DirServicio.WebService1Soap)(this)).ObtenerIntegrantesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DirServicio.InsertarNuevoIntegrateResponse> DirServicio.WebService1Soap.InsertarNuevoIntegrateAsync(DirServicio.InsertarNuevoIntegrateRequest request)
        {
            return base.Channel.InsertarNuevoIntegrateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DirServicio.InsertarNuevoIntegrateResponse> InsertarNuevoIntegrateAsync(string nombre, string nommedio, string apellido, string sexo, System.DateTime fnacim, int ciudadnac, int nacionalidad, int padre, int madre, int esposo, int esposa)
        {
            DirServicio.InsertarNuevoIntegrateRequest inValue = new DirServicio.InsertarNuevoIntegrateRequest();
            inValue.Body = new DirServicio.InsertarNuevoIntegrateRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.nommedio = nommedio;
            inValue.Body.apellido = apellido;
            inValue.Body.sexo = sexo;
            inValue.Body.fnacim = fnacim;
            inValue.Body.ciudadnac = ciudadnac;
            inValue.Body.nacionalidad = nacionalidad;
            inValue.Body.padre = padre;
            inValue.Body.madre = madre;
            inValue.Body.esposo = esposo;
            inValue.Body.esposa = esposa;
            return ((DirServicio.WebService1Soap)(this)).InsertarNuevoIntegrateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DirServicio.ObtenerFamiliaresResponse> DirServicio.WebService1Soap.ObtenerFamiliaresAsync(DirServicio.ObtenerFamiliaresRequest request)
        {
            return base.Channel.ObtenerFamiliaresAsync(request);
        }
        
        public System.Threading.Tasks.Task<DirServicio.ObtenerFamiliaresResponse> ObtenerFamiliaresAsync()
        {
            DirServicio.ObtenerFamiliaresRequest inValue = new DirServicio.ObtenerFamiliaresRequest();
            inValue.Body = new DirServicio.ObtenerFamiliaresRequestBody();
            return ((DirServicio.WebService1Soap)(this)).ObtenerFamiliaresAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/GenoServicio/webservice1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/GenoServicio/webservice1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
